### ISSUE TITLE
Het is gebruikelijk om de styling eerst algemeen te definieren en dan uitzonderingen te maken

### ISSUE THREAD

**Issue by JeroenHeemskerk** [RobHesseling/educom-webshop-basis#17]
Ik zie in de CSS staan
https://github.com/RobHesseling/educom-webshop-basis/blob/484b2af9f4f8501ecb46c09d62d3a33f51e82dba/CSS/stylesheet.css#L37-L43

hier maak je voor een select aantal typen een specifieke styling, als ik dan een ander type toevoeg, heeft deze niet deze styling. 
Het is beter om bijv. alles 400px te maken en dan voor bijv. de button een uitzondering te maken
```css
input {
	width: 400px;
} 
input[type='button'] {
	width: auto;
}
```
